server:
  name: "seckill-mall"
  mode: "debug"

mysql:
  dsn: "root:password@tcp(127.0.0.1:3306)/seckill..."

redis:
  addr: "localhost:6379"
  password: "password"
  db: 0

etcd:
  addr: "127.0.0.1:2379"