global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'product-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:9091']

  - job_name: 'order-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:9092']