server:
  name: "mq-consumer"
  mode: "debug"
  metrics_port: "9093"

mysql:
  dsn: "root:123456@tcp(127.0.0.1:3306)/seckill?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "localhost:6379"
  password: "123456"
  db: 0

#预备用到了Etcd或其他配置
etcd:
  addr: "127.0.0.1:2379"