server:
  name: "order-service"
  port: "50052"
  metrics_port: "9092"
  mode: "debug"

mysql:
  dsn: "root:123456@tcp(127.0.0.1:3306)/seckill?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "localhost:6379"
  password: "123456"
  db: 1

etcd:
  addr: "127.0.0.1:2379"

seckill:
  purchase_limit: 5 #配置限购件数

jwt:
  expire: "5s"

grpc_client:
  product_service: "localhost:50051"